#!/usr/bin/env bash
#Script to generate 2 random numbers print them and their sq roots

ran_1=$RANDOM
ran_2=$RANDOM
sqrt1=$(echo "scale=0;sqrt($ran_1)" | bc )
sqrt2=$(echo "scale=0;sqrt($ran_2)" | bc )
sum=`expr $sqrt1 + $sqrt2`
echo "The first random number generated is $ran_1"
echo "The square root is $sqrt1"
echo "The second random number generated is $ran_2"
echo "The square root is $sqrt2"
echo "The sum of their square roots is $sum"
